[project]
name = 'Gradelink'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Gradelink]
path = 'contracts/Gradelink.clar'
clarity_version = 3
epoch = 3.1

[contracts.AcademicIntegrity]
path = 'contracts/AcademicIntegrity.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
